PersonalSA/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('base.urls')),
    path('todolist/', include('todolist.urls')),
    path("account/", include("accounts.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include("api.urls"))
]

accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"
urlpatterns = [
    path("register/", views.registerUser, name="register-user"),
    #TODO: make a page for displaying user info and apps they can access
    path("login/", views.loginUser, name="login-user"),
    path("logout/", views.userLogout, name="logout-user"),
    path("<str:pk>/", views.userProfile, name="user-profile"),


]

api/urls.py
from django.urls import include, path, re_path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = "api"
urlpatterns = [
    path("users/", views.userList, name="user-list"),
    path("tasks/<str:pk>/", views.taskList, name="task-list"),
]
urlpatterns = format_suffix_patterns(urlpatterns)

base/urls.py
from django.urls import path
from . import views

app_name = "base"
urlpatterns = [
    path('', views.indexPage, name='index')
]

todolist/urls.py
from django.urls import path, re_path, include
from . import views

app_name = "todolist"
urlpatterns = [
    path('', views.toDoList_Index, name='tdlindex'),

]

frontend/models.py
from django.db import models

# Create your models here.

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=50, unique=False)
    description = models.CharField(max_length=200, unique=False, null=True, blank=True)
    status = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated"]

    def __str__(self):
        return "{} - {} - {}".format(self.author, self.title, self.updated)

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User

class RegisterForm(ModelForm):
    class Meta:
        model= User
        fields = ["first_name", "last_name", "email", "username", "password" ]

class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ["email", "password"]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from .forms import RegisterForm
from base.views import indexPage


def registerUser(request):
    form = RegisterForm()
    # When user submits the info, it'll process it
    if request.method == "POST":
        username = request.POST.get("username")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        login(request, user)
        return redirect("/")
            
    # the login page 
    context = {"form":form}
    return render(request, "accounts/registerpage.html", context)


def loginUser(request):

    if request.user.is_authenticated:
        return HttpResponse("you are already logged in!")

    if request.method == "POST":
            user = get_object_or_404(User, username = request.POST.get('username'))
            if user.check_password(request.POST.get("password")):
                login(request, user)
                redirect("/")
            else:
                return HttpResponse("password is wrong. try logging in  again")
    return render(request, "accounts/loginpage.html")

def userLogout(request):
     if request.method == "POST":
          next = request.POST.get("next")
          logout(request)
          return redirect(next)


     return render(request, "accounts/logout-confirm.html")


def userProfile(request, pk):
     user = get_object_or_404(User, username=pk)
     return render(request, "accounts/user-profile.html", {"user":user})

api/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status
from rest_framework.parsers import JSONParser
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import userSerializer, taskSerializer
from todolist.models import Task
from django.contrib.auth.models import User

@api_view(["POST", "GET"])
def userList(request, format=None):
    users = User.objects.all()
    if request.method == "GET":
        serializer = userSerializer(users, many=True)
        return Response(serializer.data)


@api_view(["POST", "GET"])
def taskList(request, pk, format=None):
    try:
        tasks = Task.objects.filter(author__username=pk)
    except Task.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    
    if request.method == "GET":
        serializer = taskSerializer(tasks, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = taskSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

base/views.py
from django.shortcuts import render
from django.http import HttpResponse

def indexPage(request):
    return render(request, "base/index.html")

frontend/views.py
from django.shortcuts import render

# Create your views here.

todolist/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Task

@login_required(login_url="accounts:login-user")
def toDoList_Index(request):
    user = request.user
    context = {}
    if user.is_authenticated:
        tasks = user.task_set.all()
        context.update({"tasks":tasks})

    if request.method == "POST":
        title = request.POST.get('task-title')
        description = request.POST.get('task-description')
        new_task = Task.objects.create(title=title, description=description, author=user)
        #TODO: use js to  make a dynamic field pop up
        return redirect('tdlindex')

    return render(request, "todolist/tdl_index.html", context)

accounts/templates/accounts/loginpage.html
{% extends "main.html" %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="username here..." >
    <br>
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="password here...">
    <br>
    <input type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/accounts/logout-confirm.html
{% extends "main.html" %}

{% block content %}
<strong>Are you sure you want to logout?</strong>
<form  method="post">
    {% csrf_token %}
    <button type="submit" >Logout</button>
    <input type="hidden" name="next" value="{{request.META.HTTP_REFERER}}">
</form>
<a href="{{request.META.HTTP_REFERER}}">Go Back</a>
{% endblock %}

accounts/templates/accounts/registerpage.html
{% extends "main.html" %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <label for="first_name">First Name:</label>
    <input type="text" name="first_name" placeholder="first name here...">
    <br>
    <label for="last_name">Last Name:</label>
    <input type="text" name="last_name" placeholder="last name here...">
    <br>
    <label for="email">Email:</label>
    <input type="email" name="email" placeholder="email here...">
    <br>
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="username here...">
    <br>
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="password here...">
    <br>
    <input type="submit" value="submit"/>
</form>
{% endblock %}







<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>

</body>
</html> -->

accounts/templates/accounts/user-profile.html
{% extends "main.html" %}


{% block content %}
<h3>{{user.first_name}} {{user.last_name}}</h3>
<h6>{{user.username}}</h6>
{% endblock content %}

base/templates/base/index.html
{% extends "main.html" %}

{% block content %}
<div id="main" class="container">
    <h2>Welcome to my site!</h2>
    {% if request.user.is_authenticated %}
    <p>this works</p>
    {% endif %}
</div>
{% endblock content %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Personal Super App</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% load static %}

    {% block content %}

    {% endblock content %}
</body>

{% block scripts %}

{% endblock scripts %}

</html>

templates/navbar.html
<div class="navbar">
    <a href="{% url 'base:index' %}">
        <h1>Logo</h1>
    </a>
    {% if request.user.is_authenticated %}
    <p>Welcome, {{request.user.first_name}}</p>
    <a href="{% url 'accounts:logout-user' %}">Logout</a>
    {% else %}
    <a href="{% url 'accounts:login-user' %}">Login</a>
    <a href="{% url 'accounts:register-user' %}">Register</a>
    {% endif %}
    <hr>
</div>

todolist/templates/todolist/tdl_index.html
{% extends "main.html" %}
{% load static %}
{% block content %}
<div id="tasks-container">
    {% if request.user.is_authenticated %}
    <div id="user-tasks">
        {% for task in tasks %}
        <div id="{{task.title}}" class="task" style="white-space: nowrap;">
            <input type="checkbox" checked="{{task.status}}" name="{{task.title}}">
            <label for="{{task.title}}"> <strong>{{task.title}} -- </strong> {{task.description}}</label>
        </div>
        {% endfor %}
    </div>
    <div id="new-task-container">
        <form method="post">
            {% csrf_token %}
            <button id="add-task-button" type="submit">+</button>
            <label for="task-title">Title:</label>
            <input type="text" name="task-title" placeholder="Enter title here...">
            <br>
            <label for="task-description">Description:</label>
            <textarea name="task-description" placeholder="Enter description here..."></textarea>
        </form>
    </div>
    {% endif %}
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'todolist/script.js' %}"></script>
{% endblock scripts %}